import Navbar from "@/components/navber/Navbar";
import Footer from "@/components/footer/Footer";
import Aos from "@/components/Aos";
import Bootstrap from "@/components/Bootstartp";
import ClientProvider from "@/rit/slices/ClientProvider";
import { NextIntlClientProvider } from "next-intl";
import { routing } from "../../../i18n/routing";
import { setRequestLocale } from "next-intl/server";
import "../globals.css";

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default async function LocaleLayout({ children, params }) {
  const locale = params.locale || routing.defaultLocale || "en";

  await setRequestLocale(locale); // مهم تضيف await هنا

  const messages = (await import(`../../../messages/${locale}.json`)).default;

  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body cz-shortcut-listen="true">
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ClientProvider>
            <Bootstrap />
            <Aos />
            <Navbar />
            {children}
            <Footer />
          </ClientProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
